---
- name: radicale | install radicale packages
  apt: name={{ item }} state=latest 
  with_items: "{{ radicale_packages }}"

- name: radicale | ensure radicale group is present
  group: name={{ radicale_group }} state=present

- name: radicale | ensure radicale user is present
  user: name={{ radicale_user }} group={{ radicale_group }} state=present

- name: radicale | create radicale user home
  file: path={{ radicale_home }} owner={{ radicale_user }} group={{ radicale_group }} mode=0700 state=directory

- name: radicale | create radicale log
  file: path={{ radicale_log }} owner={{ radicale_user }} group={{ radicale_group }} mode=0700 state=directory

- name: radicale | create filesystem folder
  file: path={{ radicale_filesystem_folder }} owner={{ radicale_user }} group={{ radicale_group }} mode=0700 state=directory

- name: radicale | configure radicale 
  template: src=config.j2 dest={{ radicale_home }}/config owner=root group=root mode=0644

- name: radicale | create systemd unit
  template: src=radicale.service.j2 dest=/etc/systemd/system/radicale.service owner=root group=root mode=0644

- name: radicale | start and enable systemd unit
  systemd: daemon_reload=yes name=radicale state=started enabled=yes
